name = "ParallelNeighbors"
uuid = "195f4218-6b04-4c05-a00e-4e57ae4ff715"
authors = ["David Muhr <muhrdavid@gmail.com> and contributors"]
version = "0.2.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"

[compat]
Distances = "0.7 - 0.10"
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "LinearAlgebra", "Suppressor", "MultivariateStats", "NearestNeighbors"]
